name: Auto-Close Stale PRs

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Get PRs with auto-delete label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const label = "auto-delete";
            const now = new Date();
            const oneMinuteAgo = new Date(now.getTime() - 60 * 1000).toISOString();

            const prs = await github.paginate(github.rest.pulls.list, {
              owner,
              repo,
              state: "open",
              per_page: 100
            });

            for (const pr of prs) {
              if (!pr.pull_request) continue; // Ignore issues, only process PRs

              const labelEvent = events.find(e => e.event === "labeled" && e.label.name === label);
                if (labelEvent && new Date(labelEvent.created_at).toISOString() < oneMinuteAgo) {
                  console.log(`Closing PR #${pr.number}`);
                  await github.rest.pulls.update({
                    owner,
                    repo,
                    pull_number: pr.number,
                    state: "closed"
                  });
                  await github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number: pr.number,
                    body: "This PR has been automatically closed after 30 days of being labelled with 'auto-delete'."
                  });
                }
              }
            }
