name: Auto-Close PRs After 1 Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

permissions:
  pull-requests: write  # Needed to close PRs
  issues: read          # Needed to read issue events

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close PRs labeled "auto-delete"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const label = "auto-delete";
            const now = new Date();
            const oneMinuteAgo = new Date(now.getTime() - 60 * 1000).toISOString();

            // Fetch all open PRs
            const prs = await github.paginate(github.rest.pulls.list, {
              owner,
              repo,
              state: "open",
              per_page: 100
            });

            for (const pr of prs) {
              // Check if PR has the "auto-delete" label
              if (!pr.labels.some(l => l.name === label)) continue;

              // Get the PR's label event timeline
              const events = await github.paginate(github.rest.issues.listEvents, {
                owner,
                repo,
                issue_number: pr.number
              });

              // Find the label added event
              const labelEvent = events.find(e => e.event === "labeled" && e.label.name === label);

              // If label added event found and is older than 1 minute, close the PR
              if (labelEvent && new Date(labelEvent.created_at).toISOString() < oneMinuteAgo) {
                console.log(`Closing PR #${pr.number}`);
                
                // Close the PR
                await github.rest.pulls.update({
                  owner,
                  repo,
                  pull_number: pr.number,
                  state: "closed"
                });

                const author = pr.user.login;

                const commentBody = `# Automatic PR Closure Notice
                ## Information
                @${pr_user} this PR has been closed automatically. It was labelled \`auto-close\` 30 days ago as part of the Unified Runtime source code migration to the intel/llvm repository - https://github.com/intel/llvm/pull/17043. 

                All Unified Runtime development should be done in [intel/llvm](https://github.com/intel/llvm/tree/sycl/unified-runtime), details can be found in the updated [contribution guide](https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html). 
                
                This repository will continue to exist as a mirror and will host the [specification documentation](https://oneapi-src.github.io/unified-runtime/).
                
                ## Next Steps
                Should you wish to re-open this PR it must be moved to [intel/llvm](https://github.com/intel/llvm/tree/sycl/unified-runtime). We have provided a [script to help automate this process](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/move-pr-to-intel-llvm.py), otherwise no actions are required.
                
                ---
                *This is an automated comment.*
                `;

                // Comment on the PR
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: pr.number,
                  body: commentBody
                });
              }
            }
