name: Label and Comment on All Open PRs

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review] 

permissions:
  pull-requests: write
  issues: read

jobs:
  label-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Label and comment on open PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const label = "auto-close";

            // Get all open pull requests
            const { data: prs } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open'  // Filter for open PRs
            });

            // Loop through each open PR
            for (const pr of prs) {
              const pr_number = pr.number;

              // Get current labels on the PR
              const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                owner,
                repo,
                issue_number: pr_number
              });

              // Check if "auto-delete" is already present
              if (!labels.some(labelObj => labelObj.name === label)) {
                // Add the label if not present
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number: pr_number,
                  labels: [label]
                });

                const author = pr.user.login;

                const commentBody = 
                  "# Unified Runtime -> intel/llvm Repo Move Notice\n" +
                  "## Information\n" +
                  "The source code of Unified Runtime has been moved to [intel/llvm](https://github.com/intel/llvm) under the [unified-runtime](https://github.com/intel/llvm/tree/sycl/unified-runtime) top-level directory,\n" +
                  "all future development will now be carried out there. This was done in https://github.com/intel/llvm/pull/17043.\n\n" +
                  "The code will be mirrored to [oneapi-src/unified-runtime](https://github.com/oneapi-src/unified-runtime) and the specification will continue to be hosted at [oneapi-src.github.io/unified-runtime](https://oneapi-src.github.io/unified-runtime/).\n" +
                  "The [contribution guide](https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html) will be updated with new instructions for contributing to Unified Runtime.\n\n" +
                  "## PR Migration\n" +
                  "All open PRs including this one will be labelled [auto-close](https://github.com/oneapi-src/unified-runtime/labels/auto-close) and shall be **automatically closed after 30 days**.\n\n" +
                  "Should you wish to continue with your PR **you will need to migrate it** to [intel/llvm](https://github.com/intel/llvm).\n" +
                  "We have provided a [script to help automate this process](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/move-pr-to-intel-llvm.py).\n\n" +
                  "If your PR should remain open and not be closed automatically, you can remove the `auto-close` label.\n\n" +
                  "---\n" +
                  "*This is an automated comment.*";

                // Add a comment about the migration process and warn the PR will be automatically closed
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: pr_number,
                  body: commentBody
                });

                console.log(`Added label '${label}' and commented on PR #${pr_number}`);
              } else {
                console.log(`PR #${pr_number} already has the '${label}' label. Skipping.`);
              }
            }
