name: Label and Comment on PR

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

permissions:
  pull-requests: write  # Only grant permission to modify PRs

jobs:
  label-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add auto-delete label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: auto-delete

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: "This PR has been marked with 'auto-delete'. It will be closed automatically if not merged within 30 days."
            });
